(()=>{'use strict';
const STORAGE='fretQuestV1';
const today=()=>{const d=new Date();return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-')};
const defaults={xp:0,history:{},difficulty:'beginner'};
let data;try{data=JSON.parse(localStorage.getItem(STORAGE))||defaults}catch{data={...defaults}}if(!data||typeof data!=='object')data={...defaults};data.xp=Number(data.xp)||0;data.history=data.history&&typeof data.history==='object'?data.history:{};data.difficulty=['beginner','intermediate','advanced'].includes(data.difficulty)?data.difficulty:'beginner';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],day=()=>data.history[today()]||{quests:[],lessons:[],extra:[],bonus:false};let activeCleanup=()=>{},toastTimeout=null,lastFocus=null,modalGeneration=0,metroGeneration=0;
const windowIcon=(name)=>'<svg class="icon" aria-hidden="true"><use href="#i-'+name+'"/></svg>';
function save(){try{localStorage.setItem(STORAGE,JSON.stringify(data));window.dispatchEvent(new Event('fq:progress'))}catch{notify('保存できません。ブラウザの設定をご確認ください。')}}
function notify(msg){const t=$('#toast');t.textContent=msg;t.classList.add('visible');clearTimeout(toastTimeout);toastTimeout=setTimeout(()=>t.classList.remove('visible'),2900)}
function daysAgo(n){const d=new Date();d.setHours(12,0,0,0);d.setDate(d.getDate()-n);return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-')}
const hasPractice=r=>!!(r?.quests?.length||r?.lessons?.length||r?.extra?.length);
/* Today's menu is one lesson, one session and one rhythm game. Older records may hold the retired daily quests. */
const menuDone=d=>!!(d?.lessons?.length&&d.extra?.some(x=>x.startsWith('jam:'))&&d.extra?.some(x=>x.startsWith('game:')));
function menuBonus(d){if(d.bonus||!menuDone(d))return 0;d.bonus=true;data.xp+=40;return 40}
function streak(){let count=0,n=0;if(!hasPractice(data.history[today()]))n=1;while(hasPractice(data.history[daysAgo(n)])){count++;n++}return count}
function render(){const d=day(),played=hasPractice(d);$('#streak-value').textContent=streak();$('#streak-sub').textContent=played?'今日もナイスプレイ！':'今日のメニューから始めよう';$('#xp-value').textContent=data.xp;const level=Math.floor(data.xp/150)+1;$('#level-value').textContent=level;$('#level-needed').textContent='NEXT '+(150-data.xp%150)+' XP';$('#xp-fill').style.width=(data.xp%150/150*100)+'%';const cal=$('#calendar-row');cal.innerHTML='';for(let i=13;i>=0;i--){const key=daysAgo(i),used=hasPractice(data.history[key]);const el=document.createElement('span');el.className='calendar-day'+(used?' active':'');el.title=key+(used?' 練習済み':' 練習なし');el.textContent=new Date(key+'T12:00:00').getDate();cal.append(el)}const days=Object.values(data.history).filter(hasPractice).length;$('#practice-days').textContent='累計'+days+'日';const badges=[['pick','初めの一歩',days>=1],['fire','3日連続',streak()>=3],['bolt','XP 300',data.xp>=300],['trophy','7日連続',streak()>=7],['music','初セッション',Object.values(data.history).some(h=>h.extra?.some(x=>x.startsWith('jam:')))],['star','メニュー完走',Object.values(data.history).some(h=>h.bonus)]];$('#badges').innerHTML=badges.map(([icon,label,yes])=>'<div class="badge '+(yes?'unlocked':'')+'" title="'+(yes?'達成済み':'未達成')+'"><div class="badge-icon">'+windowIcon(icon)+'</div><small>'+label+'</small></div>').join('');const dt=new Date();$('#today-label').textContent=new Intl.DateTimeFormat('ja-JP',{month:'long',day:'numeric',weekday:'long'}).format(dt)}


function openModal(type){modalGeneration++;$('.modal-dialog').classList.remove('is-stage');if($('#modal').hidden)lastFocus=document.activeElement;stopMetro();activeCleanup();activeCleanup=()=>{};$('#modal').hidden=false;document.body.style.overflow='hidden';$('.app-shell').inert=true;$('#modal-close').focus()}
function closeModal(){modalGeneration++;$('.modal-dialog').classList.remove('is-stage');activeCleanup();activeCleanup=()=>{};$('#modal').hidden=true;document.body.style.overflow='';$('.app-shell').inert=false;if(lastFocus?.isConnected)lastFocus.focus();else $('.nav-link[href="#courses"]')?.focus()}
$('#modal-close').onclick=closeModal;$('#modal').addEventListener('click',e=>{if(e.target===$('#modal'))closeModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('#modal').hidden)closeModal();if(e.key==='Tab'&&!$('#modal').hidden){const focusable=$$('#modal button:not(:disabled), #modal [href], #modal input');const first=focusable[0],last=focusable[focusable.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}});
function fretDiagram(string,fret,target=null){const first=Math.max(1,fret-2),y=123-string*18,x=fret===0?34:55+(fret-first+.5)*56;let s='<div class="fretboard-display"><svg viewBox="0 0 350 170" role="img" aria-label="'+(6-string)+'弦の'+(fret===0?'開放弦':fret+'フレット')+'。'+(target?'丸印の位置で'+target+'を1音鳴らしてください。':'丸印の音名を答えてください。')+'">';for(let i=0;i<6;i++){const sy=123-i*18;s+='<text x="15" y="'+(sy+3)+'" font-size="8" fill="#b3a381">'+(6-i)+'</text><line x1="55" y1="'+sy+'" x2="335" y2="'+sy+'" stroke="#c1b393" stroke-width="'+(2.6-i*.27)+'"/>';}for(let i=0;i<=5;i++)s+='<line x1="'+(55+i*56)+'" y1="30" x2="'+(55+i*56)+'" y2="126" stroke="#c1b393" stroke-width="'+(i===0&&first===1?4:1.5)+'"/>';for(let i=0;i<5;i++)s+='<text x="'+(83+i*56)+'" y="148" text-anchor="middle" font-size="8" fill="#b3a381">'+(first+i)+'</text>';s+='<circle cx="'+x+'" cy="'+y+'" r="13" fill="#c7ef75" stroke="#8ead5f" stroke-width="1.5"/><text id="spot-note" x="'+x+'" y="'+(y+4)+'" text-anchor="middle" font-size="11" font-weight="800" fill="#6d873e">'+(target||'?')+'</text></svg></div>';return s}
const chordShapes={E5:[0,2,2,-1,-1,-1],A5:[-1,0,2,2,-1,-1],D5:[-1,-1,0,2,3,-1],Em:[0,2,2,0,0,0],G:[3,2,0,0,0,3],C:[-1,3,2,0,1,0],D:[-1,-1,0,2,3,2],Am:[-1,0,2,2,1,0],F:[1,3,3,2,1,1],Bm:[-1,2,4,4,3,2],A:[-1,0,2,2,2,0],E:[0,2,2,1,0,0],'F♯m7':[2,4,2,2,2,2],B7:[-1,2,1,2,0,2],'C♯m':[-1,4,6,6,5,4],Emaj7:[0,2,1,1,0,0],'B♭':[-1,1,3,3,3,1],'G♯m':[4,6,6,4,4,4]};
/* Shapes for the phrase dojo: 7th chords, boogie double-stops, jazz shell voicings (root plus 3rd and 7th) and pop chords. */
Object.assign(chordShapes,{A7:[-1,0,2,0,2,0],D7:[-1,-1,0,2,1,2],E7:[0,2,0,1,0,0],A6:[-1,0,4,-1,-1,-1],D6:[-1,-1,0,4,-1,-1],E6:[0,4,-1,-1,-1,-1],
 Dm7:[-1,5,-1,5,6,-1],G7:[3,-1,3,4,-1,-1],Cmaj7:[-1,3,-1,4,5,-1],Cm7:[-1,3,-1,3,4,-1],F7:[1,-1,1,2,-1,-1],Bbmaj7:[6,-1,7,7,-1,-1],Ebmaj7:[-1,6,-1,7,8,-1],
 Am7b5:[5,-1,5,5,4,-1],Gm6:[3,-1,2,3,-1,-1],Gm7:[3,-1,3,3,-1,-1],Fm7:[1,-1,1,1,-1,-1],Dm7b5:[-1,5,-1,5,6,4],
 Dm:[-1,-1,0,2,3,1],Am7:[-1,0,2,0,1,0],Fmaj7:[-1,-1,3,2,1,0]});
function chordDiagram(name){const shape=chordShapes[name];if(!shape)return '';const positive=shape.filter(f=>f>0),first=Math.max(...positive)>4?Math.min(...positive):1;const barres={F:1,Bm:2,'F♯m7':2,'C♯m':4,'B♭':1,'G♯m':4},barre=barres[name],from=shape[0]===-1?1:0;let s='<svg class="chord-chart" viewBox="0 0 164 180" role="img" aria-label="'+name+'のコード図。左から6弦、右が1弦。丸は押さえる位置、白丸は開放弦、×は鳴らさない弦。">';for(let i=0;i<6;i++){const x=25+i*22;s+='<line x1="'+x+'" y1="36" x2="'+x+'" y2="140" stroke="#aab494" stroke-width="1.5"/><text x="'+x+'" y="157" text-anchor="middle" font-size="8" fill="#a3ad8c">'+(6-i)+'</text>';if(shape[i]===0)s+='<circle cx="'+x+'" cy="22" r="3.5" fill="none" stroke="#8d9e6d" stroke-width="1.3"/>';if(shape[i]===-1)s+='<path d="M'+(x-3)+' 19l6 6m0-6-6 6" stroke="#a3ad8c" stroke-width="1.3"/>';}for(let i=0;i<=4;i++)s+='<line x1="25" y1="'+(36+i*26)+'" x2="135" y2="'+(36+i*26)+'" stroke="#aab494" stroke-width="'+(i===0&&first===1?4:1.2)+'"/>';if(first>1)s+='<text x="9" y="53" font-size="8" fill="#a3ad8c">'+first+'</text>';if(barre)s+='<rect x="'+(25+from*22-6)+'" y="'+(36+(barre-first+.5)*26-6)+'" width="'+((5-from)*22+12)+'" height="12" rx="6" fill="#98b262"/>';shape.forEach((f,i)=>{if(f>0&&f!==barre)s+='<circle cx="'+(25+i*22)+'" cy="'+(36+(f-first+.5)*26)+'" r="6" fill="#7f9d49"/>';});return s+'</svg>'}

let audio=null;async function ensureAudio(){try{audio=audio||new (window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')await audio.resume()}catch{notify('この端末では音が使えません')}}function soundClick(accent=false){if(!audio||audio.state!=='running')return;const t=audio.currentTime,o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.setValueAtTime(accent?1060:740,t);o.frequency.exponentialRampToValueAtTime(accent?520:410,t+.045);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(accent?.21:.13,t+.004);g.gain.exponentialRampToValueAtTime(.0001,t+.075);o.connect(g);g.connect(audio.destination);o.start(t);o.stop(t+.08)}
let bpm=90,metroInterval=null,metroBeat=0;const dots=$$('.beat-dots span');function setBpm(n){bpm=Math.max(40,Math.min(220,n));$('#bpm-value').textContent=bpm;$('#bpm-slider').value=bpm;if(metroInterval){stopMetro();startMetro()}}function metroTick(){soundClick(metroBeat%4===0);dots.forEach((d,i)=>d.classList.toggle('lit',i===metroBeat%4));metroBeat++}async function startMetro(){const generation=++metroGeneration;await ensureAudio();if(generation!==metroGeneration)return;metroBeat=0;metroTick();metroInterval=setInterval(metroTick,60000/bpm);$('#metro-toggle').textContent='■ ストップ';$('#metro-toggle').classList.add('running');$('#metro-status').textContent='PLAYING'}function stopMetro(){metroGeneration++;clearInterval(metroInterval);metroInterval=null;dots.forEach(d=>d.classList.remove('lit'));$('#metro-toggle').textContent='▶ スタート';$('#metro-toggle').classList.remove('running');$('#metro-status').textContent='READY'}$('#metro-toggle').onclick=()=>metroInterval?stopMetro():startMetro();$$('[data-bpm]').forEach(b=>b.onclick=()=>setBpm(bpm+Number(b.dataset.bpm)));$('#bpm-slider').oninput=e=>setBpm(Number(e.target.value));$$('.nav-link').forEach(a=>a.addEventListener('click',()=>{$$('.nav-link').forEach(x=>x.classList.remove('active'));a.classList.add('active')}));document.addEventListener('visibilitychange',()=>{if(document.hidden&&metroInterval)stopMetro()});window.addEventListener('pagehide',()=>{stopMetro();activeCleanup()});render();
// The academy shares the existing save format, modal lifecycle, audio and diagrams.
const courseIds=new Set((window.FQCourses||[]).flatMap(c=>c.lessons.map(l=>l.id))),courseList=new Set((window.FQCourses||[]).map(c=>c.id));
function validState(raw){
 if(!raw||typeof raw!=='object'||Array.isArray(raw)||!Number.isFinite(raw.xp)||raw.xp<0||raw.xp>1000000)throw Error('形式が違います');
 const history={},courses={};
 for(const [date,r] of Object.entries(raw.history||{})){if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||!r||typeof r!=='object')continue;const quests=[...new Set((Array.isArray(r.quests)?r.quests:[]).filter(q=>['chord','fret','rhythm'].includes(q)))],lessons=[...new Set((Array.isArray(r.lessons)?r.lessons:[]).filter(id=>courseIds.has(id)))];const extra=[...new Set((Array.isArray(r.extra)?r.extra:[]).filter(x=>typeof x==='string'&&/^(jam|game|lick):[a-z0-9-]{1,30}$/.test(x)))].slice(0,40);history[date]={quests,lessons,extra,bonus:(quests.length===3||menuDone({lessons,extra}))&&r.bonus===true};}
 for(const [id,r] of Object.entries(raw.courses||{})){if(!courseIds.has(id)||!r||typeof r!=='object'||!Number.isFinite(Date.parse(r.completedAt)))continue;courses[id]={completedAt:new Date(r.completedAt).toISOString(),bestScore:Math.max(0,Math.min(100,Number(r.bestScore)||0)),attempts:Math.max(1,Math.min(100000,Number(r.attempts)||1)),method:['microphone','self','quiz','tap','ear'].includes(r.method)?r.method:'self'};}
 /* Courses opened by a skip challenge or by hand, and experienced mode (everything open). */
 const unlocked=[...new Set((Array.isArray(raw.unlocked)?raw.unlocked:[]).filter(id=>courseList.has(id)))];
 return {xp:Math.floor(raw.xp),history,courses,unlocked,experienced:raw.experienced===true,difficulty:['beginner','intermediate','advanced'].includes(raw.difficulty)?raw.difficulty:'beginner'};
}
/* Best scores of sessions and games live in their own keys; export them and keep the higher value on import. */
function bests(key){try{return JSON.parse(localStorage.getItem(key))?.best||{}}catch{return {}}}
function mergeBests(key,incoming){if(!incoming||typeof incoming!=='object')return;let stored={};try{stored=JSON.parse(localStorage.getItem(key))||{}}catch{}stored.best=stored.best||{};for(const [id,v] of Object.entries(incoming)){if(/^[a-z0-9-]{1,30}$/.test(id)&&Number.isFinite(v)&&v>=0&&v<1e7)stored.best[id]=Math.max(Number(stored.best[id])||0,v)}try{localStorage.setItem(key,JSON.stringify(stored))}catch{}}
function ledger(s){return Object.values(s.history||{}).reduce((sum,d)=>sum+(d.quests?.length||0)*30+(d.extra?.length||0)*20+(d.bonus?40:0),0)+Object.keys(s.courses||{}).length*40;}
window.FretQuest={
 getState:()=>JSON.parse(JSON.stringify(data)),today,notify,icon:windowIcon,chordDiagram,fretDiagram,
 show:fn=>{openModal('academy');fn($('#modal-inner'));},close:closeModal,setCleanup:fn=>{activeCleanup=fn;},generation:()=>modalGeneration,ensureAudio,
 playTone:async(midi,duration=.6,delay=0)=>{await ensureAudio();if(!audio||audio.state!=='running')return false;const o=audio.createOscillator(),g=audio.createGain(),t=audio.currentTime+delay;o.type='triangle';o.frequency.value=440*Math.pow(2,(midi-69)/12);g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(.09,t+.015);g.gain.exponentialRampToValueAtTime(.0001,t+duration);o.connect(g);g.connect(audio.destination);o.start(t);o.stop(t+duration+.02);return true;},
 click:soundClick,streak,audioContext:()=>audio,chordShape:name=>chordShapes[name]||null,
 recordLesson:(id,score,method)=>{if(!courseIds.has(id))return 0;data.courses=data.courses||{};const old=data.courses[id];data.courses[id]={completedAt:old?.completedAt||new Date().toISOString(),bestScore:Math.max(old?.bestScore||0,score),attempts:(old?.attempts||0)+1,method};const d=day();d.lessons=[...new Set([...(d.lessons||[]),id])];data.history[today()]=d;let earned=old?0:40;data.xp+=earned;earned+=menuBonus(d);save();render();return earned;},
 /* Sessions and rhythm games: 20 XP the first time each one is played on a day. */
 recordActivity:id=>{if(!/^(jam|game|lick):[a-z0-9-]{1,30}$/.test(id))return 0;const d=day();d.extra=d.extra||[];let earned=0;if(!d.extra.includes(id)){d.extra.push(id);earned=20;data.xp+=20;}data.history[today()]=d;earned+=menuBonus(d);save();render();return earned;},
 unlockCourse:id=>{if(!courseList.has(id))return;data.unlocked=[...new Set([...(data.unlocked||[]),id])];save();render();},
 setExperienced:on=>{data.experienced=!!on;save();render();},
 menuStatus:()=>{const d=day();return {lesson:!!d.lessons?.length,jam:!!d.extra?.some(x=>x.startsWith('jam:')),game:!!d.extra?.some(x=>x.startsWith('game:')),bonus:!!d.bonus};},
 exportState:()=>({app:'FRET_QUEST',version:2,exportedAt:new Date().toISOString(),state:JSON.parse(JSON.stringify(data)),bests:{jam:bests('fretQuestJam'),games:bests('fretQuestGames')}}),
 importState:backup=>{if(backup?.app!=='FRET_QUEST'||backup.version!==2)throw Error('FRET QUESTの記録ファイルを選んでください。');const incoming=validState(backup.state),current=validState(data),merged=validState(data);for(const [date,r] of Object.entries(incoming.history)){const old=merged.history[date]||{quests:[],lessons:[],extra:[],bonus:false};merged.history[date]={quests:[...new Set([...old.quests,...r.quests])],lessons:[...new Set([...old.lessons,...r.lessons])],extra:[...new Set([...(old.extra||[]),...r.extra])],bonus:old.bonus||r.bonus};if(merged.history[date].quests.length===3||menuDone(merged.history[date]))merged.history[date].bonus=true;}for(const [id,r] of Object.entries(incoming.courses)){const old=merged.courses[id];merged.courses[id]=old?{completedAt:old.completedAt<r.completedAt?old.completedAt:r.completedAt,bestScore:Math.max(old.bestScore,r.bestScore),attempts:Math.max(old.attempts,r.attempts),method:old.method}:r;}merged.xp=Math.max(0,current.xp-ledger(current),incoming.xp-ledger(incoming))+ledger(merged);merged.unlocked=[...new Set([...merged.unlocked,...incoming.unlocked])];merged.experienced=merged.experienced||incoming.experienced;mergeBests('fretQuestJam',backup.bests?.jam);mergeBests('fretQuestGames',backup.bests?.games);data=merged;save();render();notify('記録を読み込みました。重複したクリアはまとめています。');}
};
})();
